### ISSUE TITLE
[Widget] New: "Notes widget"

### ISSUE THREAD

**Issue by alachaum** [maestrano/impac-angular#31]
As stupid as it sounds, I actually think this would be useful :)

A simple notes widget with several tabs to record ToDos and other useful information.

**Comment by xaun** [comment]
Haha, I think that's a really good idea @alachaum... Partly because the OCD within me loves notes / organisational apps :)  Would it makes sense to click on chart data and reference it in notes? 

Looks like chart.js has a on click callback function prototypes available:
```
canvas.onclick = function(evt){
    var activePoints = myLineChart.getPointsAtEvent(evt);
    // => activePoints is an array of points on the canvas that are at the same position as the click event.
};
```

**Comment by alachaum** [comment]
I like it!
Are you thinking of referencing a value in the notes? And/Or creating an actual link that would automatically scroll down and highlight the widget upon clicking on the reference?

**Comment by xaun** [comment]
Say, clicking on a Liability Summary pie graph account and selecting "create note" > focuses notes widget > creates note with title "Liability Summary | Date.now()" > fills note details section with details of data at the point > focuses body for your note. 
And yeah, the title of the widget acts as a link to highlighting the widget it references.

**Comment by alachaum** [comment]
I believe that can be cool :)

**Comment by cesar-tonnoir** [comment]
Yep. À 'toolbox' category with notes, calendars and check-lists is already
planned in the roadmap ;)

I also like the idea of linking it to charts, which is quite simple using
the new lib

**Comment by cesar-tonnoir** [comment]
https://maestrano.atlassian.net/browse/IMPAC-71
