### ISSUE TITLE
[ChartJs] Growth Per Product - Widget - Graph Off

### ISSUE THREAD

**Issue by Boulay365** [maestrano/impac-angular#44]
This is in Cake Factory organisation of John Doe. 
<img width="985" alt="screen shot 2015-11-23 at 17 07 01" src="https://cloud.githubusercontent.com/assets/15724955/11350706/ed8ff88e-9286-11e5-8c86-2a693c0d7f04.png">

**Comment by cesar-tonnoir** [comment]
https://maestrano.atlassian.net/browse/IMPAC-120

**Comment by cesar-tonnoir** [comment]
Fixed with update to Chart.js 2.1.4
